KB = 1024
MB = 1024 * KB
GB = 1024 * MB

DISK_SIZE_IN_BYTES = 16 * MB

IMAGE_FPATH = 'disk.img'

BYTES_PER_SECTOR = 512
BYTES_PER_BLOCK = 4 * KB
SECTORS_PER_BLOCK = BYTES_PER_BLOCK // BYTES_PER_SECTOR

N_RESERVED_BLOCKS = 256
I_META_BLOCK = 256  # 1MB for MBR and kernel image
I_BITMAP_BLOCK = I_META_BLOCK + 1

TYPE_DIRECTORY = 0x01
TYPE_FILE = 0x02
